id: https://hotecosystem.org/tccm/valuesetresolution
name: valuesetresolution
title: Value Set Resolution
license: https://creativecommons.org/publicdomain/zero/1.0/
description: |-
  ValueSet definitions can be resolved dynamically on an as needed basis, but they also can be transferred between
  systems without the necessity of maintaining complete copies of the code system versions that are used to resolve
  them. This model defines the output of a value set resolution request. It contains sufficient information that the
  request can be completely reproduced against a service instance the mirrors the state of the system doing the
  resolution. It also carries the result of the resolution that can be transferred and loaded into a system that
  does not mirror the source system state.

prefixes:
  tccm: https://hotecosystem.org/tccm/
  biolinkml: https://w3id.org/biolink/biolinkml/

default_prefix: tccm
default_range: string

imports:
  - ../core/prefixes
  - ../core/entityreference
  - ../core/references
  - ../core/filters
  - ../core/resourcedescription
  - ../core/entrydescription



classes:
  ResolvedValueSetHeader:
    description: The information required to completely resolve a value set definition.
    comments:
      - >-
        A ResolvedValueSetHeader entry carries all of the information that is necessary to completely resolve a value
        set, meaning that

    attributes:
      resolutionOf:
        description: The specific value set definition that was resolved.
        range: ValueSetDefinitionReference
        inlined: true
        required: true
      resolvedUsingCodeSystem:
        description: A reference to a code system version that was used in the resolution of this value set definition.
        range: CodeSystemVersionReference
        inlined: true
        multivalued: true
      includesResolvedValueSet:
        description: |-
          If the value set includes other value sets, this contains the resolution information used to resolve the inner
          value sets.
        range: ResolvedValueSetHeader
        inlined: true
        multivalued: true


